### PR TITLE
Use correct output size for AES on z platform

### LINKED ISSUE #240: Fix AES cipher output size issue for z/OS and LOZ
When the fast command is enabled, the AES cipher does not return the correct output size on z/OS.

The simplified failing test on z/OS and LoZ:

```
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import java.nio.ByteBuffer;

public class TestAesCbc {

    public static void main(String[] args) throws Exception {
        testAesCbc();
    }

    private static void testAesCbc() throws Exception {
        byte[] data = new byte[1500];
        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding", "OpenJCEPlus");
        KeyGenerator kg = KeyGenerator.getInstance("AES");
        SecretKey key = kg.generateKey();
        cipher.init(Cipher.ENCRYPT_MODE, key, cipher.getParameters());
        ByteBuffer in = ByteBuffer.allocateDirect(data.length);
        ByteBuffer out = ByteBuffer.allocateDirect(cipher.getOutputSize(data.length));
        int updateLen = data.length / 2;
        in.limit(updateLen);
        cipher.update(in, out);
        in.limit(in.capacity());
        cipher.doFinal(in, out);
    }
}
```

The failing JDK test: https://github.com/openjdk/jdk/blob/master/test/jdk/javax/crypto/CipherSpi/ResetByteBuffer.java

**Root Cause:**

The issue happens when the `use_z_fast_command` is enabled for z platforms only.
It uses a different buffer and the `engineGetOutputSize2` method.
However, the AESCipher getOutputSize was not using that method, causing the issue and returning the wrong output size on z platforms.

**Fix:**

The `engineGetOutputSize2` should be renamed to the `getOutputSizeForZ`.
Then in the `engineGetOutputSize` method, the `use_z_fast_command` should be checked.
If it is true, then it should return `getOutputSizeForZ`.
Otherwise, it returns `symmetricCipher.getOutputSize`.

### PR DESCRIPTION
**Pull request by jasonkatonica**
When the fast z command is available the AES cipher does not return the correct output size on platform z.

Platform z uses a different buffer and output size calculation. The method `engineGetOutputSize` when running on platform z should return and take this into account.

A new test was added to exercise byte buffers and various combinations of encryption, decryption, and orders of doFinal and update operations which can be used to recreate the problem.

Closes #240

Signed-off-by: Jason Katonica <katonica@us.ibm.com>

### CODE REVIEW

**Review by johnpeck-us-ibm — APPROVED** [review]

**Review by JinhangZhang — APPROVED** [review]
LGTM

File: src/main/java/com/ibm/crypto/plus/provider/AESCipher.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ protected byte[] engineDoFinal(byte[] input, int inputOffset, int inputLen)
             byte[] output = null;
             int outputLen = -1;
             if (use_z_fast_command) {
-                output = new byte[engineGetOutputSize2(inputLen)];
+                output = new byte[getOutputSizeForZ(inputLen)];
```
Comment (KostasTsiounis) [inline src/main/java/com/ibm/crypto/plus/provider/AESCipher.java:62]: Since the `engineGetOutputSize()` now checks `use_z_fast_command`, do we really need the if-else statement here?

File: src/test/java/ibm/jceplus/junit/base/BaseTestResetByteBuffer.java [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+            initializeEncrypt(direct);
+        } else {
+            initializeDecrypt(direct);
+        }
+
+        // Perform first operation, either an update or dofinal.
+        if (updateFirst == true) {
+            doUpdate();
+        } else {
+            doFinal();
```
Comment (KostasTsiounis) [inline src/test/java/ibm/jceplus/junit/base/BaseTestResetByteBuffer.java:82]: Should we add a `return` here to avoid potentially wrong parameters?

File: src/test/java/ibm/jceplus/junit/base/BaseTestResetByteBuffer.java [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+        }
+
+        // Perform second operation, either an update or dofinal.
+        if (updateSecond == true) {
+            doUpdate();
+        } else {
+            doFinal();
+        }
```
Comment (KostasTsiounis) [inline src/test/java/ibm/jceplus/junit/base/BaseTestResetByteBuffer.java:90]: Should we also include an additional `doFinal()` in case 2 updates were performed?

File: src/test/java/ibm/jceplus/junit/openjceplus/TestResetByteBuffer.java [hunk 4]
```diff
@@ -0,0 +1,24 @@
+/*
+ * Copyright IBM Corp. 2024
+ *
+ * Licensed under the Apache License 2.0 (the "License").  You may not use
+ * this file except in compliance with the License.  You can obtain a copy
+ * in the file LICENSE in the source distribution.
+ */
+
+package ibm.jceplus.junit.openjceplus;
```
Comment (KostasTsiounis) [inline src/test/java/ibm/jceplus/junit/openjceplus/TestResetByteBuffer.java:9]: Does this test not apply to the FIPS provider too?

**Review by KostasTsiounis — CHANGES_REQUESTED** [review]

File: src/main/java/com/ibm/crypto/plus/provider/AESCipher.java (hunk 1 above)
Comment (jasonkatonica) [reply src/main/java/com/ibm/crypto/plus/provider/AESCipher.java]: Yes good point here. I was able to simplify this spot with commit https://github.com/IBM/OpenJCEPlus/pull/263/commits/64d8350ad66b6459c4c9e3629a90b9cf7194c1db since the methods `engineGetOutputSize` and also `engineDoFinal` both handle the logic associated with `use_z_fast_command`.

File: src/test/java/ibm/jceplus/junit/base/BaseTestResetByteBuffer.java (hunk 2 above)
Comment (jasonkatonica) [reply src/test/java/ibm/jceplus/junit/base/BaseTestResetByteBuffer.java:82]: I don't believe that we want to do a return at this spot. A `doFinal()` operation should restore the state of the Cipher to the state it was prior to making the call. It should be initalized and ready for another operation ( either an update or doFinal ) after this doFinal() completes.

File: src/test/java/ibm/jceplus/junit/base/BaseTestResetByteBuffer.java (hunk 3 above)
Comment (jasonkatonica) [reply src/test/java/ibm/jceplus/junit/base/BaseTestResetByteBuffer.java:90]: I don't believe that we want do finalize a double update. This test is just intended to make sure that no exceptions occur with various combinations of `doUpdate` and `doFinal` calls and that the output buffer sizes are calculated correctly.

File: src/test/java/ibm/jceplus/junit/openjceplus/TestResetByteBuffer.java (hunk 4 above)
Comment (jasonkatonica) [reply src/test/java/ibm/jceplus/junit/openjceplus/TestResetByteBuffer.java:9]: This did cross my mind that perhaps we wanted to test this with the OpenJCEPlusFIPS provider in addition to just OpenJCEPlus. The code through both these paths should be identical. This being said better safe then sorry so I turned this test on for OpenJCEPlusFIPS with updates in commit https://github.com/IBM/OpenJCEPlus/commit/64d8350ad66b6459c4c9e3629a90b9cf7194c1db

**Review by KostasTsiounis — APPROVED** [review]
LGTM
