### PR TITLE
Fix memory leak computing ECDH secrets

### LINKED ISSUE #387: Memory leak in XECKEY computeECDHSecret
By placing the test `BaseTestXDH` classes variation `testXDH_X25519` into a tight loop with many iterations it can be observed that the following context is leaking as per a leak report:
```
STACK OF 1894953 INSTANCES OF 'ROOT LEAK: <malloc in CRYPTO_zalloc>':
4   ???                                   0x16e74be7c 0x7fffffffffffffff + 9223372043002887805
3   libjgskit.dylib                       0x107fb5880 Java_com_ibm_crypto_plus_provider_ock_NativeInterface_XECKEY_1computeECDHSecret + 148
2   libicclib085.dylib                    0x1157e57d8 int_ctx_new + 212
1   libicclib085.dylib                    0x1157cd558 CRYPTO_zalloc + 76
0   libsystem_malloc.dylib                0x19419a840 _malloc_zone_malloc_instrumented_or_legacy + 264 
====
    9466824 (867M) << TOTAL >>
      ----
      34 (3.20K) ROOT LEAK: <malloc in CRYPTO_zalloc 0x505c18f40> [80]
         29 (2.73K) <malloc in CRYPTO_zalloc 0x505c19560> [80]
            27 (2.45K) <malloc in CRYPTO_zalloc 0x505c195b0> [80]
               25 (2.34K) unaligned +27:  --> <malloc in omrmem_allocate_memory 0x117519f20> [96]
                  24 (2.25K) <malloc in omrmem_allocate_memory 0x117477910> [96]
                     23 (2.16K) <malloc in omrmem_allocate_memory 0x10870f4e0> [96]
                        22 (2.06K) <malloc in omrmem_allocate_memory 0x12681d920> [96]
                           21 (1.97K) <malloc in omrmem_allocate_memory 0x10800c450> [96]
                              20 (1.88K) <malloc in omrmem_allocate_memory 0x1171c6a30> [96]
                                 19 (1.78K) <malloc in omrmem_allocate_memory 0x116dc2f10> [96]
                                    18 (1.69K) <malloc in omrmem_allocate_memory 0x116dc1380> [96]
                                       17 (1.59K) <malloc in omrmem_allocate_memory 0x12681dfa0> [96]
                                          16 (1.50K) <malloc in omrmem_allocate_memory 0x116ef06d0> [96]
                                             15 (1.41K) <malloc in omrmem_allocate_memory 0x1171c66d0> [96]
                                                14 (1.31K) <malloc in omrmem_allocate_memory 0x12681d840> [96]
                                                   13 (1.22K) <malloc in omrmem_allocate_memory 0x12760b730> [96]
                                                      12 (1.12K) <malloc in omrmem_allocate_memory 0x10870c3d0> [96]
                                                         11 (1.03K) <malloc in omrmem_allocate_memory 0x115cbee50> [96]
                                                            10 (960 bytes) <malloc in omrmem_allocate_memory 0x116dc1e00> [96]
                                                               9 (864 bytes) <malloc in omrmem_allocate_memory 0x1172bcbb0> [96]
                                                                  8 (768 bytes) <malloc in omrmem_allocate_memory 0x10870dad0> [96]
                                                                     7 (672 bytes) <malloc in omrmem_allocate_memory 0x12681cee0> [96]
                                                                        6 (576 bytes) <malloc in omrmem_allocate_memory 0x1172cda60> [96]
                                                                           5 (480 bytes) <malloc in omrmem_allocate_memory 0x1376dacd0> [96]
                                                                              4 (384 bytes) <malloc in omrmem_allocate_memory 0x117469a70> [96]
                                                                                 3 (288 bytes) <malloc in omrmem_allocate_memory 0x10800b710> [96]
                                                                                    2 (192 bytes) <malloc in omrmem_allocate_memory 0x11644b360> [96]
                                                                                       1 (96 bytes) <malloc in omrmem_allocate_memory 0x1171c60b0> [96]
               1 (32 bytes) <malloc in ecx_key_op 0x505c193e0> [32]
            1 (208 bytes) <pthread_rwlock_t 0x505c19660> [208]
         4 (400 bytes) <malloc in CRYPTO_zalloc 0x505c19310> [80]
            1 (208 bytes) <pthread_rwlock_t 0x505c19490> [208]
            2 (112 bytes) <malloc in CRYPTO_zalloc 0x505c19410> [80]
               1 (32 bytes) <malloc in ecx_key_op 0x505c19460> [32]
      ----
      10 (960 bytes) ROOT LEAK: <malloc in CRYPTO_zalloc 0x1208efc10> [80]
         5 (480 bytes) <malloc in CRYPTO_zalloc 0x1208effe0> [80]
            1 (208 bytes) <pthread_rwlock_t 0x1208f0160> [208]
            3 (192 bytes) <malloc in CRYPTO_zalloc 0x1208f00e0> [80]
               1 (80 bytes) unaligned +27:  --> <malloc in CRYPTO_zalloc 0x124c15260> [80]
               1 (32 bytes) <malloc in ecx_key_op 0x1208f0130> [32]
         4 (400 bytes) <malloc in CRYPTO_zalloc 0x1208f0230> [80]
            1 (208 bytes) <pthread_rwlock_t 0x1208f0330> [208]
            2 (112 bytes) <malloc in CRYPTO_zalloc 0x1208f0280> [80]
               1 (32 bytes) <malloc in ecx_key_op 0x1208f00b0> [32]
      ----
      10 (960 bytes) ROOT LEAK: <malloc in CRYPTO_zalloc 0x120c32a60> [80]
         5 (480 bytes) <malloc in CRYPTO_zalloc 0x120c32e30> [80]
            1 (208 bytes) <pthread_rwlock_t 0x120c32fb0> [208]
            3 (192 bytes) <malloc in CRYPTO_zalloc 0x120c32f30> [80]
               1 (80 bytes) unaligned +27:  --> <malloc in CRYPTO_zalloc 0x116129f90> [80]
               1 (32 bytes) <malloc in ecx_key_op 0x120c32f80> [32]
         4 (400 bytes) <malloc in CRYPTO_zalloc 0x120c33080> [80]
            1 (208 bytes) <pthread_rwlock_t 0x120c33180> [208]
            2 (112 bytes) <malloc in CRYPTO_zalloc 0x120c330d0> [80]
               1 (32 bytes) <malloc in ecx_key_op 0x120c32f00> [32]
             
...
...
ADDITONAL ENTRIES SIMILAR TO ABOVE REDACTED
...
```

The context being allocated on this line is never released:

https://github.com/IBM/OpenJCEPlus/blob/8711f8323f906c7435d6e250ff9eab2fced2c35a/src/main/native/ECKey.c#L2127

### PR DESCRIPTION
**Pull request by jasonkatonica**
The context allocated in the method `XECKEY.computeECDHSecret` was never freed when a key was successfully generated. This update frees memory associated with the context prior to return of the secret key bytes.

Whitespace and formatting was also done to make use of brackets for if statements.

Fixes #387

Signed-off-by: Jason Katonica <katonica@us.ibm.com>

### CODE REVIEW

File: src/main/native/ECKey.c [hunk 1]
```diff
@@ -2121,12 +2121,14 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
   jbyteArray           retSecretBytes = NULL;
   size_t               secret_key_len = 0;
 
-  
-  if( debug ) gslogFunctionEntry(functionName);
+  if( debug ) {
```
Comment (KostasTsiounis) [inline src/main/native/ECKey.c:2124]: Can we fix the spaces in the parentheses too?

File: src/main/native/ECKey.c [hunk 2]
```diff
@@ -2121,12 +2121,14 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
...
+    gslogFunctionEntry(functionName);
+  }
 
   gen_ctx = ICC_EVP_PKEY_CTX_new(ockCtx,(ICC_EVP_PKEY *) ockPrivXecKey,NULL); /* Set private key */
-  if(gen_ctx == NULL) throwOCKException(env, 0, "NULL from ICC_EVP_PKEY_CTX_new"); 
-  else {
+  if ( NULL == gen_ctx ) {
```
Comment (KostasTsiounis) [inline src/main/native/ECKey.c:2129]: Can we fix the spaces in the parentheses too?

File: src/main/native/ECKey.c [hunk 3]
```diff
@@ -2135,28 +2137,44 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
         ICC_EVP_PKEY_derive(ockCtx, gen_ctx, NULL, &secret_key_len); /* Get secret key size */
     }
     secretBytes = (*env)->NewByteArray(env, secret_key_len); /* Create Java secret bytes array with size */
-    if( secretBytes == NULL ) throwOCKException(env, 0, "NewByteArray failed"); 
-    else {
+    if( NULL == secretBytes ) {
```
Comment (KostasTsiounis) [inline src/main/native/ECKey.c:2140]: Can we fix the spaces in the parentheses too?

File: src/main/native/ECKey.c [hunk 4]
```diff
@@ -2135,28 +2137,44 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
...
+      throwOCKException(env, 0, "NewByteArray failed"); 
+    } else {
       secretBytesNative = (unsigned char*)((*env)->GetPrimitiveArrayCritical(env, secretBytes, &isCopy));
-      if( secretBytesNative == NULL ) throwOCKException(env, 0, "NULL from GetPrimitiveArrayCritical"); 
-      else {
+      if( NULL == secretBytesNative ) {
```
Comment (KostasTsiounis) [inline src/main/native/ECKey.c:2144]: Can we fix the spaces in the parentheses too?

File: src/main/native/ECKey.c [hunk 5]
```diff
@@ -2135,28 +2137,44 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
...
         retSecretBytes = secretBytes;
-        if( secretBytesNative != NULL ) (*env)->ReleasePrimitiveArrayCritical(env, secretBytes, secretBytesNative, 0);
-        if((secretBytes != NULL) && (retSecretBytes == NULL)) (*env)->DeleteLocalRef(env, secretBytes);
-        if( debug ) gslogFunctionExit(functionName);
+        ICC_EVP_PKEY_CTX_free(ockCtx, gen_ctx);
+        (*env)->ReleasePrimitiveArrayCritical(env, secretBytes, secretBytesNative, 0);
+        if( NULL == retSecretBytes ) {
+          (*env)->DeleteLocalRef(env, secretBytes);
+        }
+        if( debug ) {
```
Comment (KostasTsiounis) [inline src/main/native/ECKey.c:2154]: Can we fix the spaces in the parentheses too?

File: src/main/native/ECKey.c [hunk 6]
```diff
@@ -2135,28 +2137,44 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
...
+        throwOCKException(env, 0, "NULL from GetPrimitiveArrayCritical");
+      } else {
         ICC_EVP_PKEY_derive(ockCtx, gen_ctx, secretBytesNative, &secret_key_len);
         retSecretBytes = secretBytes;
-        if( secretBytesNative != NULL ) (*env)->ReleasePrimitiveArrayCritical(env, secretBytes, secretBytesNative, 0);
-        if((secretBytes != NULL) && (retSecretBytes == NULL)) (*env)->DeleteLocalRef(env, secretBytes);
-        if( debug ) gslogFunctionExit(functionName);
+        ICC_EVP_PKEY_CTX_free(ockCtx, gen_ctx);
+        (*env)->ReleasePrimitiveArrayCritical(env, secretBytes, secretBytesNative, 0);
+        if( NULL == retSecretBytes ) {
```
Comment (KostasTsiounis) [inline src/main/native/ECKey.c:2151]: I'm not sure how we could get in here.

File: src/main/native/ECKey.c [hunk 7]
```diff
@@ -2135,28 +2137,44 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
...
-  if( debug ) gslogFunctionExit(functionName);
+  if (NULL != gen_ctx) {
+    ICC_EVP_PKEY_CTX_free(ockCtx, gen_ctx);
+  }
+
+  if( NULL != secretBytesNative ) {
+    (*env)->ReleasePrimitiveArrayCritical(env, secretBytes, secretBytesNative, 0);
+  }
+
+  if( ( NULL != secretBytes ) && ( NULL == retSecretBytes ) ) {
```
Comment (KostasTsiounis) [inline src/main/native/ECKey.c:2170]: I think `NULL != secretBytes` is enough, since we only get here if something goes wrong and `retSecretBytes` is never assigned a value.

File: src/main/native/ECKey.c [hunk 8]
```diff
@@ -2135,28 +2137,44 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
...
   }
 
-  if( secretBytesNative != NULL ) (*env)->ReleasePrimitiveArrayCritical(env, secretBytes, secretBytesNative, 0);
-  if((secretBytes != NULL) && (retSecretBytes == NULL)) (*env)->DeleteLocalRef(env, secretBytes);
-  if( debug ) gslogFunctionExit(functionName);
+  if (NULL != gen_ctx) {
+    ICC_EVP_PKEY_CTX_free(ockCtx, gen_ctx);
+  }
+
+  if( NULL != secretBytesNative ) {
```
Comment (KostasTsiounis) [inline src/main/native/ECKey.c:2166]: Can we fix the spaces in the parentheses too?

File: src/main/native/ECKey.c [hunk 9]
```diff
@@ -2135,28 +2137,44 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
...
+    (*env)->ReleasePrimitiveArrayCritical(env, secretBytes, secretBytesNative, 0);
+  }
+
+  if( ( NULL != secretBytes ) && ( NULL == retSecretBytes ) ) {
+    (*env)->DeleteLocalRef(env, secretBytes);
+  }
+
+  if( debug ) {
```
Comment (KostasTsiounis) [inline src/main/native/ECKey.c:2174]: Can we fix the spaces in the parentheses too?

**Review by KostasTsiounis — CHANGES_REQUESTED** [review]

File: src/main/native/ECKey.c (hunk 6 above)
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: Yes agreed given that we check that `secreteBytes` is not NULL above and we set `retSecretBytes` to `secreteBytes`. After further inspection i could not figure out why we needed both `secreteBytes` and `retSecretBytes`. I eliminated `retSecretBytes`. Hopefully this looks better now?

File: src/main/native/ECKey.c (hunk 7 above)
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: Yes agreed i also eliminated the variable `retSecretBytes` so this is not necessary.

File: src/main/native/ECKey.c (hunk 8 above)
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: Removed the spaces in the parentheses here and other locations in this method.

File: src/main/native/ECKey.c (hunk 5 above)
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: Removed the spaces in the parentheses here and other locations in this method.

File: src/main/native/ECKey.c (hunk 4 above)
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: Removed the spaces in the parentheses here and other locations in this method.

File: src/main/native/ECKey.c (hunk 3 above)
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: Removed the spaces in the parentheses here and other locations in this method.

File: src/main/native/ECKey.c (hunk 2 above)
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: Removed the spaces in the parentheses here and other locations in this method.

File: src/main/native/ECKey.c (hunk 1 above)
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: Removed the spaces in the parentheses here and other locations in this method.

In the long run we should prob decide on some sort of tooling or set of rules that can be used to reformat all of the C code to make it more consistant. We currently have the style.xml settings which are available and documented in the README file however this set of rules does not apply to C code. Enforing style via tooling is much easier and effecient then through code reviews :)

**Review by johnpeck-us-ibm — APPROVED** [review]

**Review by JinhangZhang — APPROVED** [review]
LGTM

File: src/main/native/ECKey.c [hunk 10]
```diff
@@ -2135,28 +2136,40 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
...
     secretBytes = (*env)->NewByteArray(env, secret_key_len); /* Create Java secret bytes array with size */
-    if( secretBytes == NULL ) throwOCKException(env, 0, "NewByteArray failed"); 
-    else {
+    if(NULL == secretBytes) {
+      throwOCKException(env, 0, "NewByteArray failed"); 
+    } else {
       secretBytesNative = (unsigned char*)((*env)->GetPrimitiveArrayCritical(env, secretBytes, &isCopy));
-      if( secretBytesNative == NULL ) throwOCKException(env, 0, "NULL from GetPrimitiveArrayCritical"); 
-      else {
+      if(NULL == secretBytesNative) {
```
Comment (JinhangZhang) [inline src/main/native/ECKey.c:2143]: same as here, we should ad. one space after `if`.

**Review by taoliult — APPROVED** [review]
LGTM

File: src/main/native/ECKey.c (hunk 10 above)
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: I added spaces right after if statement in various locations. Hopefully this looks better now.

File: src/main/native/ECKey.c [hunk 11]
```diff
@@ -2135,28 +2136,40 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
         ICC_EVP_PKEY_derive(ockCtx, gen_ctx, NULL, &secret_key_len); /* Get secret key size */
     }
     secretBytes = (*env)->NewByteArray(env, secret_key_len); /* Create Java secret bytes array with size */
-    if( secretBytes == NULL ) throwOCKException(env, 0, "NewByteArray failed"); 
-    else {
+    if(NULL == secretBytes) {
```
[the remark this answers is not in the document]
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: I added spaces right after if statement in various locations. Hopefully this looks better now.

File: src/main/native/ECKey.c [hunk 12]
```diff
@@ -2135,28 +2136,40 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
...
+      throwOCKException(env, 0, "NewByteArray failed"); 
+    } else {
       secretBytesNative = (unsigned char*)((*env)->GetPrimitiveArrayCritical(env, secretBytes, &isCopy));
-      if( secretBytesNative == NULL ) throwOCKException(env, 0, "NULL from GetPrimitiveArrayCritical"); 
-      else {
+      if(NULL == secretBytesNative) {
+        throwOCKException(env, 0, "NULL from GetPrimitiveArrayCritical");
+      } else {
         ICC_EVP_PKEY_derive(ockCtx, gen_ctx, secretBytesNative, &secret_key_len);
```
[the remark this answers is not in the document]
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: I added an additional check for the return code that is returned from `ICC_EVP_PKEY_derive` [these updates](https://github.com/IBM/OpenJCEPlus/pull/393/commits/869abb03c06f202ad57ece9a40a403a558ff55ff) required the logic in a test to be updated since the exception returned is now different then before.

File: src/main/native/ECKey.c [hunk 13]
```diff
@@ -2135,28 +2137,43 @@ JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeInterfa
...
-        retSecretBytes = secretBytes;
-        if( secretBytesNative != NULL ) (*env)->ReleasePrimitiveArrayCritical(env, secretBytes, secretBytesNative, 0);
-        if((secretBytes != NULL) && (retSecretBytes == NULL)) (*env)->DeleteLocalRef(env, secretBytes);
-        if( debug ) gslogFunctionExit(functionName);
-        return retSecretBytes;
+      if (NULL == secretBytesNative) {
+        throwOCKException(env, 0, "NULL from GetPrimitiveArrayCritical");
+      } else {
+        rc = ICC_EVP_PKEY_derive(ockCtx, gen_ctx, secretBytesNative, &secret_key_len);
+        if (rc != ICC_OSSL_SUCCESS) {
```
Comment (KostasTsiounis) [inline src/main/native/ECKey.c:2148]: Should we have the constant first?

File: src/test/java/ibm/jceplus/junit/base/BaseTestXDH.java [hunk 14]
```diff
@@ -336,20 +337,10 @@ private void runSmallOrderTest() throws Exception {
     private void testSmallOrder(String name, String a_pri, String b_pub, String result)
             throws Exception {
 
-        try {
-            //System.out.println("Pub - "+b_pub);
+        Exception thrown = Assertions.assertThrows(IllegalStateException.class, () -> {
```
Comment (KostasTsiounis) [inline src/test/java/ibm/jceplus/junit/base/BaseTestXDH.java:340]: What about the other types of exceptions that were caught before? Are they not a possibility anymore?

**Review by KostasTsiounis — CHANGES_REQUESTED** [review]

File: src/main/native/ECKey.c (hunk 13 above)
Comment (jasonkatonica) [reply src/main/native/ECKey.c]: Yes, I moved the constant first in latest updates.

File: src/test/java/ibm/jceplus/junit/base/BaseTestXDH.java (hunk 14 above)
Comment (jasonkatonica) [reply src/test/java/ibm/jceplus/junit/base/BaseTestXDH.java]: With the updates in place when providing a small value as this test is intending we should only get an `IllegalStateException` now with the given updates in the C method which now returns the exception. Also please note i needed to remove the Junit 5 syntax in this spot since it was failing with an error `IllegalAccess Class 'class ibm.jceplus.junit.base.BaseTestXDH' no access to: class 'interface org.junit.jupiter.api.function.Executable'` which I have not been able to resolve. Syntax was reverted back to try catch as was present previously.

**Review by KostasTsiounis — APPROVED** [review]
LGTM
